### ISSUE TITLE
Negative comments from people leaving.

### ISSUE THREAD

**Issue by NoxyNixie** [LeMinaw/skywanderers-bot#1]
I'd like to request the removal of negative comments from the bot as this influences the atmosphere in the chat.

Specifically any messages related to people leaving or being banned.

I'm also fine with turning them in a more positive message though this may be hard.

**Comment by LeMinaw** [comment]
Thanks for your feedback.
I removed the "we will not remember you" thing, but for now I'll keep the Portal 2 ending quote, because I think people can easily spot the reference / the irony of it.
Does that sounds right to you?

**Comment by NoxyNixie** [comment]
It has gotten better yes, though I initially did not see the reference to portal just thought the bot was rude, until someone actually said it was a reference.

I still think an automated system should not convey any emotion or content that can be perceived as emotional as it can alter the mood of a channel or conversation.

I might be an old fart when it comes to these things but back in the IRC days we tended to frown upon quit/leaving/goodbye/away messages. So I may have grown a strong dislike to them from the past.
